[package]
name = "adk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
compat = ["dep:adk-codec"]
runtime = ["dep:adk-runtime"]

[dependencies]
adk-core.workspace = true
adk-codec = { workspace = true, optional = true }
adk-runtime = { workspace = true, optional = true }

[dev-dependencies]
tokio.workspace = true

[[example]]
name = "runner"
required-features = ["runtime"]
